### ISSUE TITLE
Numba needs NumPy 1.20 or less

### ISSUE THREAD

**Issue by daron-m-standley** [Liuxg16/GeoPPI#7]
Hi, I just installed GeoPPI on a RH linux system. Everything in the instal instructions went smoothly (very nice instructions!). But, when I tried to run the example, I got the above error. The full output (with my home dir replaced by `<myhome>`) is:
```
(ppi) bash-4.2$ python run.py data/testExamples/1PPF.pdb  TI17F  E_I
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from models import *
  File "<myhome>/standley/code/git/GeoPPI/models.py", line 4, in <module>
    from torch_geometric.data import DataLoader
  File "<myhome>/code/miniconda2/envs/ppi/lib/python3.8/site-packages/torch_geometric/__init__.py", line 5, in <module>
    import torch_geometric.transforms
  File "<myhome>/code/miniconda2/envs/ppi/lib/python3.8/site-packages/torch_geometric/transforms/__init__.py", line 36, in <module>
    from .gdc import GDC
  File "<myhome>/code/miniconda2/envs/ppi/lib/python3.8/site-packages/torch_geometric/transforms/gdc.py", line 2, in <module>
    import numba
  File "<myhome>/code/miniconda2/envs/ppi/lib/python3.8/site-packages/numba/__init__.py", line 198, in <module>
    _ensure_critical_deps()
  File "<mypath>miniconda2/envs/ppi/lib/python3.8/site-packages/numba/__init__.py", line 138, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.20 or less")
```
I tried deactivating and reactivating the ppi environment, but that didn't help. Have you seen this error before?

**Comment by daron-m-standley** [comment]
When I force conda to install numpy 1.20, I get other errors:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - numpy=1.20 -> python[version='>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']

Your python: python=2.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0
  - numpy=1.20 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17

```

**Comment by JIN-DAI** [comment]
Hi, I met the same "ImportError("Numba needs NumPy 1.20 or less")" when I run this project with Python 3.8.5 and MacOSX 12.1. 
I force conda to install numba then this error is fixed.

**Comment by renee9904** [comment]
Hi, I have some similar problem in running this project. Instead of those error, I got
```
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    import torch, pickle
ModuleNotFoundError: No module named 'torch'
```
But it was installed before, have you run into this error?
I really appreciate any helps.
